ingest:
  tz: "UTC"
  min_events_per_cohort: 5

features:
  night_hours: [22, 23, 0, 1, 2, 3, 4, 5, 6]
  ladder_max_gap_days: 3
  gap_percentiles: [50, 95]
  min_gap_seconds: 0.1
  max_gap_seconds: 3600

scoring:
  weights:
    cadence: 0.2
    repetition: 0.25
    speed: 0.15
    hygiene: 0.15
    protocol: 0.1
    volume: 0.05
    ip_churn: 0.1
  alpha_blend_iso: 0.5
  thresholds:
    high: 0.75
    medium: 0.55
    low: 0.25

isolation_forest:
  n_estimators: 300
  contamination: 0.05
  random_state: 42
  max_samples: 0.8

history:
  ewma_alpha_7d: 0.3
  ewma_alpha_30d: 0.1
  lookback_days: 30

io:
  input_dir: "data/raw"
  features_dir: "data/features"
  history_dir: "data/history"
  reports_dir: "reports"

reporting:
  top_n_cohorts: 50
  sample_rows_per_cohort: 3
  include_evidence: true
